
name: Test101

on: [push]

jobs:
  myfirstrun:
    runs-on: ubuntu-latest
    name: The First Run
    steps:
    - name: Just do it
      run: pwd; ls -l; echo "higher"; ls -l ..; ant -buildfile ../build.xml compile jar run



