
name: Test101

on: [push]

jobs:
  myfirstrun:
    runs-on: ubuntu-latest
    name: The First Run
    steps:
    - uses: actions/checkout@v2
    - name: Just do it
      run: ant -noinput -buildfile build.xml compile jar run



