
name: Test101

on: [push]

jobs:
  myfirstrun:
    runs-on: ubuntu-latest
    name: The First Run
    steps:
    - name: Just do it
      run: pwd; ls -al; echo "higher"; ls -al ../; echo "ecen higher"; ls -al ../../ ; ant -noinput -buildfile ../build.xml compile jar run



